-- External variable database definition for MySQL 5.7
-- Generated 12/8/16 7:43 PM
-- Descriptor: Metrics/BTS_metrics.xvar (currently edited)
-- External variable BTS_Request
DROP TABLE IF EXISTS BTS_Request;
CREATE TABLE BTS_Request (REQUESTID VARCHAR(250), CUSTOMERID INTEGER, EVENTTYPE VARCHAR(250), EVENTDATETIME DATETIME, EVENTDURATION INTEGER, URGENCY VARCHAR(250), REQUESTTYPE VARCHAR(250), LOCATION VARCHAR(250), STATUS VARCHAR(250), ASSIGNEDROUTE VARCHAR(250), ROUTERCOST NUMERIC, HSANREQUIRED BOOLEAN, HSANCOST NUMERIC, EXTERNALRESOURCEREQUIRED BOOLEAN, APPROVALNEEDED BOOLEAN, APPROVED BOOLEAN, PROPOSAL VARCHAR(250), MODIFIED_ON DATETIME, EXTERNAL_STARTED_ON DATETIME, EXTERNAL_ENDED_ON DATETIME, HSAN_STARTED_ON DATETIME, HSAN_ENDED_ON DATETIME, VALUATED_ON DATETIME, APPROVAL_REQUESTED_ON DATETIME, APPROVAL_RECEIVED_ON DATETIME, CREATED_ON DATETIME, UPDATED_ON DATETIME, PROCESS_ID VARCHAR(250), INSTANCE_ID INTEGER) ENGINE = innodb;
CREATE INDEX BTS_Request_KEYS ON BTS_Request (REQUESTID);

